---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"

- hosts: nginxservers
  become: yes
  tasks:
    - name: update
      apt: update_cache=yes
    - name: Install Nginx
      apt: name=nginx state=latest
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded
