---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"

    - name: Install the latest version of Apache
      ansible.builtin.dnf:
          name: *
          state: latest
    

