---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"

    - name: Install the latest version of Apache
      ansible.builtin.dnf:
          name: *
          state: latest
          register: patch_update 
          became: true
    
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
      when: patch_update is changed 
      msg: "Rebooting machine in 5 seconds"

